import type { BudgetAllocation, CountryId, CountryProfile, TaxPolicy } from '@/types';

/**
 * 게임용 초기값. 실제 통계를 그대로 옮기지 않고, 8개국이 서로 다른 전략을
 * 요구하도록 조정한 수치다. 모든 금액 단위는 10억 USD(연율)이다.
 */
export interface InitialCountryData extends CountryProfile {
  gdp: number;
  population: number;
  /** 게임 시작 시점의 추세 성장률(%). 생산성 목표 calibration 에 쓰인다. */
  trendGrowth: number;

  consumptionShare: number;
  investmentShare: number;
  exportShare: number;
  importShare: number;

  inflation: number;
  unemployment: number;
  policyRate: number;
  productivity: number;
  competitiveness: number;
  energyDependence: number;

  fertilityRate: number;
  mortalityRate: number;
  lifeExpectancy: number;
  workingAgeShare: number;
  elderlyShare: number;
  migrationRate: number;
  educationIndex: number;

  approval: number;
  stability: number;

  debtToGdp: number;
  /** GDP 대비 재정수지(%). 음수면 적자. 세외수입 calibration 의 기준이 된다. */
  fiscalBalanceRatio: number;

  tax: TaxPolicy;
  budget: BudgetAllocation;

  troops: number;
  militaryTech: number;
  militaryReadiness: number;
}

const budget = (
  welfare: number,
  education: number,
  defense: number,
  healthcare: number,
  security: number,
  infrastructure: number,
  research: number,
  environment: number,
  industry: number,
): BudgetAllocation => ({
  welfare,
  education,
  defense,
  healthcare,
  security,
  infrastructure,
  research,
  environment,
  industry,
});

export const COUNTRIES: Record<CountryId, InitialCountryData> = {
  KOR: {
    id: 'KOR',
    name: '대한민국',
    shortName: '한국',
    personality: 'economic',
    bloc: 'asia',
    gdp: 1_950,
    population: 51_200_000,
    trendGrowth: 1.9,
    consumptionShare: 48,
    investmentShare: 32,
    exportShare: 44,
    importShare: 41,
    inflation: 2.3,
    unemployment: 3.0,
    policyRate: 3.0,
    productivity: 96,
    competitiveness: 80,
    energyDependence: 88,
    fertilityRate: 0.75,
    mortalityRate: 6.6,
    lifeExpectancy: 83.5,
    workingAgeShare: 70,
    elderlyShare: 19.5,
    migrationRate: 0.6,
    educationIndex: 82,
    approval: 42,
    stability: 68,
    debtToGdp: 52,
    fiscalBalanceRatio: -2.5,
    tax: { income: 22, corporate: 24, consumption: 10 },
    budget: budget(6.0, 4.0, 2.6, 4.0, 1.2, 3.0, 1.1, 0.7, 1.2),
    troops: 500_000,
    militaryTech: 76,
    militaryReadiness: 78,
  },
  USA: {
    id: 'USA',
    name: '미국',
    shortName: '미국',
    personality: 'aggressive',
    bloc: 'americas',
    gdp: 28_500,
    population: 335_000_000,
    trendGrowth: 1.8,
    consumptionShare: 68,
    investmentShare: 21,
    exportShare: 11,
    importShare: 14,
    inflation: 2.9,
    unemployment: 4.1,
    policyRate: 4.5,
    productivity: 118,
    competitiveness: 84,
    energyDependence: 12,
    fertilityRate: 1.62,
    mortalityRate: 9.3,
    lifeExpectancy: 79.0,
    workingAgeShare: 65,
    elderlyShare: 17.5,
    migrationRate: 2.8,
    educationIndex: 78,
    approval: 45,
    stability: 62,
    debtToGdp: 121,
    fiscalBalanceRatio: -6.5,
    tax: { income: 27, corporate: 21, consumption: 6 },
    budget: budget(8.0, 4.8, 3.4, 8.6, 2.0, 2.4, 0.9, 0.5, 0.8),
    troops: 1_320_000,
    militaryTech: 95,
    militaryReadiness: 85,
  },
  JPN: {
    id: 'JPN',
    name: '일본',
    shortName: '일본',
    personality: 'diplomatic',
    bloc: 'asia',
    gdp: 4_200,
    population: 123_500_000,
    trendGrowth: 0.7,
    consumptionShare: 55,
    investmentShare: 26,
    exportShare: 21,
    importShare: 22,
    inflation: 2.6,
    unemployment: 2.6,
    policyRate: 0.5,
    productivity: 92,
    competitiveness: 76,
    energyDependence: 92,
    fertilityRate: 1.2,
    mortalityRate: 12.0,
    lifeExpectancy: 84.5,
    workingAgeShare: 59,
    elderlyShare: 29.5,
    migrationRate: 0.7,
    educationIndex: 80,
    approval: 38,
    stability: 72,
    debtToGdp: 250,
    fiscalBalanceRatio: -4.5,
    tax: { income: 24, corporate: 23, consumption: 10 },
    budget: budget(11.0, 3.2, 1.6, 7.8, 1.2, 3.4, 0.7, 0.7, 1.0),
    troops: 250_000,
    militaryTech: 82,
    militaryReadiness: 70,
  },
  CHN: {
    id: 'CHN',
    name: '중국',
    shortName: '중국',
    personality: 'aggressive',
    bloc: 'asia',
    gdp: 18_500,
    population: 1_410_000_000,
    trendGrowth: 3.6,
    consumptionShare: 39,
    investmentShare: 41,
    exportShare: 20,
    importShare: 17,
    inflation: 1.0,
    unemployment: 5.1,
    policyRate: 3.1,
    productivity: 62,
    competitiveness: 78,
    energyDependence: 72,
    fertilityRate: 1.05,
    mortalityRate: 7.8,
    lifeExpectancy: 78.5,
    workingAgeShare: 68,
    elderlyShare: 15.5,
    migrationRate: -0.3,
    educationIndex: 66,
    approval: 58,
    stability: 74,
    debtToGdp: 85,
    fiscalBalanceRatio: -6.5,
    tax: { income: 20, corporate: 25, consumption: 13 },
    budget: budget(5.0, 3.6, 1.7, 3.0, 2.4, 6.0, 1.0, 1.2, 2.4),
    troops: 2_035_000,
    militaryTech: 80,
    militaryReadiness: 75,
  },
  DEU: {
    id: 'DEU',
    name: '독일',
    shortName: '독일',
    personality: 'economic',
    bloc: 'europe',
    gdp: 4_600,
    population: 84_500_000,
    trendGrowth: 0.9,
    consumptionShare: 52,
    investmentShare: 22,
    exportShare: 43,
    importShare: 39,
    inflation: 2.2,
    unemployment: 5.9,
    policyRate: 2.4,
    productivity: 108,
    competitiveness: 82,
    energyDependence: 65,
    fertilityRate: 1.38,
    mortalityRate: 11.8,
    lifeExpectancy: 81.3,
    workingAgeShare: 64,
    elderlyShare: 22.5,
    migrationRate: 4.0,
    educationIndex: 79,
    approval: 40,
    stability: 70,
    debtToGdp: 63,
    fiscalBalanceRatio: -2.0,
    tax: { income: 29, corporate: 30, consumption: 19 },
    budget: budget(12.5, 4.5, 2.1, 7.8, 1.6, 2.4, 1.1, 1.0, 1.2),
    troops: 183_000,
    militaryTech: 78,
    militaryReadiness: 62,
  },
  FRA: {
    id: 'FRA',
    name: '프랑스',
    shortName: '프랑스',
    personality: 'diplomatic',
    bloc: 'europe',
    gdp: 3_200,
    population: 68_400_000,
    trendGrowth: 0.9,
    consumptionShare: 54,
    investmentShare: 24,
    exportShare: 33,
    importShare: 36,
    inflation: 2.1,
    unemployment: 7.4,
    policyRate: 2.4,
    productivity: 104,
    competitiveness: 72,
    energyDependence: 44,
    fertilityRate: 1.62,
    mortalityRate: 9.5,
    lifeExpectancy: 82.8,
    workingAgeShare: 61,
    elderlyShare: 21.8,
    migrationRate: 1.5,
    educationIndex: 77,
    approval: 34,
    stability: 60,
    debtToGdp: 114,
    fiscalBalanceRatio: -5.5,
    tax: { income: 31, corporate: 26, consumption: 20 },
    budget: budget(15.0, 5.2, 2.0, 8.4, 1.7, 2.8, 1.0, 1.1, 1.4),
    troops: 205_000,
    militaryTech: 80,
    militaryReadiness: 72,
  },
  GBR: {
    id: 'GBR',
    name: '영국',
    shortName: '영국',
    personality: 'isolationist',
    bloc: 'europe',
    gdp: 3_400,
    population: 68_900_000,
    trendGrowth: 1.1,
    consumptionShare: 62,
    investmentShare: 18,
    exportShare: 30,
    importShare: 33,
    inflation: 2.7,
    unemployment: 4.4,
    policyRate: 4.0,
    productivity: 101,
    competitiveness: 74,
    energyDependence: 55,
    fertilityRate: 1.44,
    mortalityRate: 9.2,
    lifeExpectancy: 81.0,
    workingAgeShare: 63,
    elderlyShare: 19.2,
    migrationRate: 3.4,
    educationIndex: 78,
    approval: 36,
    stability: 63,
    debtToGdp: 100,
    fiscalBalanceRatio: -4.5,
    tax: { income: 30, corporate: 25, consumption: 20 },
    budget: budget(11.0, 4.4, 2.3, 8.0, 1.8, 2.5, 0.8, 0.7, 0.9),
    troops: 148_000,
    militaryTech: 83,
    militaryReadiness: 70,
  },
  IND: {
    id: 'IND',
    name: '인도',
    shortName: '인도',
    personality: 'neutral',
    bloc: 'asia',
    gdp: 4_100,
    population: 1_440_000_000,
    trendGrowth: 4.5,
    consumptionShare: 60,
    investmentShare: 31,
    exportShare: 22,
    importShare: 25,
    inflation: 4.8,
    unemployment: 8.0,
    policyRate: 6.3,
    productivity: 34,
    competitiveness: 58,
    energyDependence: 78,
    fertilityRate: 1.95,
    mortalityRate: 7.2,
    lifeExpectancy: 70.5,
    workingAgeShare: 68,
    elderlyShare: 7.2,
    migrationRate: -0.4,
    educationIndex: 52,
    approval: 55,
    stability: 58,
    debtToGdp: 83,
    fiscalBalanceRatio: -8.0,
    tax: { income: 16, corporate: 25, consumption: 12 },
    budget: budget(3.2, 3.0, 2.4, 2.1, 1.5, 4.2, 0.7, 0.6, 1.4),
    troops: 1_455_000,
    militaryTech: 66,
    militaryReadiness: 65,
  },
};

/**
 * 예산 항목 중 실제로 정부가 재화·서비스를 직접 구매하는 비중.
 * 나머지는 이전지출로 가계 소비에 흡수된다. GDP 항등식 계산에 쓰인다.
 */
export const DIRECT_PURCHASE_SHARE: BudgetAllocation = {
  welfare: 0.15,
  education: 0.9,
  defense: 1.0,
  healthcare: 0.7,
  security: 1.0,
  infrastructure: 1.0,
  research: 0.9,
  environment: 0.9,
  industry: 0.4,
};

export const COUNTRY_LIST = Object.values(COUNTRIES);
